### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by HolyPacket** [TogAr2/MinestomPvP#28]
> java.lang.NoSuchMethodError: 'void net.minestom.server.network.packet.server.play.SoundEffectPacket.<init>(net.minestom.server.sound.SoundEvent, net.kyori.adventure.sound.Sound$Source, net.minestom.server.coordinate.Point, float, float)'
        at Ext_PvpExtension//io.github.bloepiloepi.pvp.listeners.DamageListener.handleEntityDamage(DamageListener.java:377)
        at Ext_PvpExtension//io.github.bloepiloepi.pvp.listeners.DamageListener.lambda$events$0(DamageListener.java:56)
        at net.minestom.server.event.EventListener$Builder$1.run(EventListener.java:151)
        at net.minestom.server.event.EventNodeImpl$Handle.callListener(EventNodeImpl.java:488)
        at net.minestom.server.event.EventNodeImpl$Handle.lambda$listenersConsumer$8(EventNodeImpl.java:420)
        at net.minestom.server.event.EventNodeImpl$Handle.lambda$createConsumer$5(EventNodeImpl.java:391)
        at net.minestom.server.event.EventNodeImpl$Handle.lambda$createConsumer$5(EventNodeImpl.java:399)
        at net.minestom.server.event.EventNodeImpl$Handle.lambda$createConsumer$5(EventNodeImpl.java:399)
        at net.minestom.server.event.EventNodeImpl$Handle.lambda$createConsumer$5(EventNodeImpl.java:399)
        at net.minestom.server.event.EventNodeImpl$Handle.call(EventNodeImpl.java:324)
        at net.minestom.server.event.EventNode.call(EventNode.java:190)
        at net.minestom.server.event.EventNode.callCancellable(EventNode.java:215)
        at net.minestom.server.event.EventDispatcher.callCancellable(EventDispatcher.java:18)
        at net.minestom.server.entity.LivingEntity.damage(LivingEntity.java:340)
        at Ext_PvpExtension//io.github.bloepiloepi.pvp.listeners.FallDamageHandler.handleFallDamage(FallDamageHandler.java:81)
        at Ext_PvpExtension//io.github.bloepiloepi.pvp.listeners.DamageListener.lambda$events$2(DamageListener.java:72)
        at net.minestom.server.event.EventListener$Builder$1.run(EventListener.java:151)
        at net.minestom.server.event.EventNodeImpl$Handle.callListener(EventNodeImpl.java:488)
        at net.minestom.server.event.EventNodeImpl$Handle.lambda$listenersConsumer$8(EventNodeImpl.java:420)
        at net.minestom.server.event.EventNodeImpl$Handle.lambda$createConsumer$5(EventNodeImpl.java:391)
        at net.minestom.server.event.EventNodeImpl$Handle.lambda$createConsumer$5(EventNodeImpl.java:399)
        at net.minestom.server.event.EventNodeImpl$Handle.lambda$createConsumer$5(EventNodeImpl.java:399)
        at net.minestom.server.event.EventNodeImpl$Handle.lambda$createConsumer$5(EventNodeImpl.java:399)
        at net.minestom.server.event.EventNodeImpl$Handle.call(EventNodeImpl.java:324)
        at net.minestom.server.event.EventNode.call(EventNode.java:190)
        at net.minestom.server.event.EventDispatcher.call(EventDispatcher.java:10)
        at net.minestom.server.listener.PlayerPositionListener.processMovement(PlayerPositionListener.java:57)
        at net.minestom.server.listener.PlayerPositionListener.playerPositionListener(PlayerPositionListener.java:24)
        at net.minestom.server.listener.manager.PacketListenerManager.processClientPacket(PacketListenerManager.java:90)
        at net.minestom.server.entity.Player.lambda$interpretPacketQueue$16(Player.java:1808)
        at org.jctools.queues.MpscUnboundedXaddArrayQueue.drain(MpscUnboundedXaddArrayQueue.java:312)
        at net.minestom.server.entity.Player.interpretPacketQueue(Player.java:1808)
        at net.minestom.server.entity.Player.update(Player.java:345)
        at net.minestom.server.entity.Entity.tick(Entity.java:541)
        at net.minestom.server.thread.TickThread.tick(TickThread.java:66)
        at net.minestom.server.thread.TickThread.run(TickThread.java:41)

**Comment by TogAr2** [comment]
This seems to me like a version mismatch between Minestom and MinestomPvP. Please let me know if the error still persists after updating.
