### ISSUE TITLE
[BUG] Materal.isFood() method does not exist

### ISSUE THREAD

**Issue by Andrei965** [TogAr2/MinestomPvP#32]
Hello! I am running minestorm 1c528d8ae2 and minestormpvp a373305fa0 and I have a issue regarding an unknown method. I have initialized minestormpvp, registered default events, and when I start the server it throws an exception:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'boolean net.minestom.server.item.Material.isFood()'
	at io.github.togar2.pvp.food.FoodComponents.loadFromRegistry(FoodComponents.java:141)
	at io.github.togar2.pvp.food.FoodComponents.registerAll(FoodComponents.java:126)
	at io.github.togar2.pvp.PvpExtension.init(PvpExtension.java:52)
```
The material class does not have the method isFood()

**Comment by TogAr2** [comment]
Hey! Looks like you are using a newer version of Minestom than the current master version of MinestomPvP supports. I am rewriting the whole thing, until then an up to date version can be found [here](https://github.com/Am-Gone/MinestomPvP)
