### ISSUE TITLE
Network Protocol Error with End Crystal

### ISSUE THREAD

**Issue by Asintotoo** [TogAr2/MinestomPvP#45]
With the `ExplosiveFeature` enabled, if you try to place an End Crystal on a block of Obsidian or Bedrock, you get kicked for "Network Protocol Error" and can't join the server back unless you restart it.
I also tried this on a simple Minestom server with minimal to none configuration and it happens too.

I momentarily found a work around to be able to still use tnt and respawn anchor features: I rewrote the `VanillaExplosiveFeature` class and remove the `PlayerUseItemOnBlockEvent` listener and everything seems to work fine (a part from crystals obviously).

**Comment by TogAr2** [comment]
As a temporary workaround it would also be possible to cancel `CrystalPlaceEvent` instead of rewriting the feature.

Will look at a fix soon.

**Comment by Sparky983** [comment]
The issue is due to the [`CrystalEntity` extending `LivingEntity`](https://github.com/TogAr2/MinestomPvP/blob/master/src/main/java/io/github/togar2/pvp/entity/explosion/CrystalEntity.java#L11) when it [should only extend `Entity`](https://wiki.vg/Entity_metadata#End_Crystal).

Client crash report:
```
java.lang.IllegalStateException: Server tried to update attributes of a non-living entity (actually: EndCrystal['End Crystal'/3, l='ClientLevel', x=27.50, y=158.00, z=-71.50])
	at Genesis//net.minecraft.client.multiplayer.ClientPacketListener.handleUpdateAttributes(SourceFile:2097)
	at Genesis//net.minecraft.network.protocol.game.ClientboundUpdateAttributesPacket.handle(SourceFile:51)
	at Genesis//net.minecraft.network.protocol.game.ClientboundUpdateAttributesPacket.handle(SourceFile:20)
	at Genesis//net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(SourceFile:27)
	at Genesis//net.minecraft.util.thread.BlockableEventLoop.doRunTask(SourceFile:162)
	at Genesis//net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(SourceFile:23)
	at Genesis//net.minecraft.util.thread.BlockableEventLoop.pollTask(SourceFile:136)
	at Genesis//net.minecraft.util.thread.BlockableEventLoop.runAllTasks(SourceFile:121)
	at Genesis//net.minecraft.client.Minecraft.runTick(SourceFile:1240)
	at Genesis//net.minecraft.client.Minecraft.run(SourceFile:882)
	at Genesis//net.minecraft.client.main.Main.main(SourceFile:256)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.moonsworth.lunar.genesis.ClientGameBootstrap.apply(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.moonsworth.lunar.genesis.COHORCHOCHOOOCHRHIHIRIICHIHIHO.RROCOCCHRORIORIHOROCORCIHHHICC(Unknown Source)
	at com.moonsworth.lunar.genesis.Genesis.run(Unknown Source)
	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
```

**Comment by im-a-blobfish** [comment]
One simple way to fix this would be to just cancel any EntityAttributesPacket where the entity is an instance of CrystalEntity, although this is sort of a hacky fix. It does work though, I tested it.

This code stops the error.

```
		MinecraftServer.getGlobalEventHandler().addListener(PlayerPacketOutEvent.class, event -> {
			if (event.getPacket() instanceof EntityAttributesPacket entityAttributesPacket) {
				if (instance.getEntityById(entityAttributesPacket.entityId()) instanceof CrystalEntity) {
					event.setCancelled(true);
				}
			}
		});
```
